### ISSUE TITLE
E-mail d'inscription

### ISSUE THREAD

**Issue by TokaLazy** [malnuxstarck/Sitedusavoir#37]
Il faudrait changer l'url dans l'email d'inscription.

**Comment by malnuxstarck** [comment]
Qu'est ce tu propose... l'URL contient lid et un token pour verivière quila
s'agit bien de la personne...

**Comment by TokaLazy** [comment]
Je parle du nom de domaine. Sur l'email on a ce lien : https://sitedusavoir.com
Alors que je suis sur le site http://malnux.shost.ca

**Comment by malnuxstarck** [comment]
😂😂😂... Ah oui sert toi.. j'avais oublier en faite le domaine à été
fermer car je voulais pas le renouveller.. On a changer le nom du projet en
un autre nom.. Oui vas y tu as raison...

**Comment by TokaLazy** [comment]
Je pense que tu peux te baser sur l'url du nom de domaine avec `$_SERVER`, ce sera plus simple au cas ou tu changes encore 😝

**Comment by malnuxstarck** [comment]
Merci de me le signaler

**Comment by TokaLazy** [comment]
`$_SERVER["SERVER_NAME"]` (mon message d'avant n'était pas très précis)

**Comment by malnuxstarck** [comment]
J'avais déjà compris 😀😀😀
