### ISSUE TITLE
Utiliser editorconfig

### ISSUE THREAD

**Issue by TokaLazy** [malnuxstarck/Sitedusavoir#39]
Editorconfig est un plugin pratique pour éviter de commit à rallonge à cause des différences de tabulation par exemple.

http://editorconfig.org

En gros, un fichier de configuration avec des règles défini pour tous permet d'avoir la même indentation. Ce qui évite ce genre de chose : https://github.com/TokaLazy/Sitedusavoir/commit/6f8eb1b2ec760a8979bafef3ad115a914c6de788#diff-9e3c41566678054af064231cd0d0045a

Voila un exemple de configuration : https://gist.github.com/TokaLazy/c59d785e3c411209e795df52a6d4cf59

**Comment by malnuxstarck** [comment]
ça me semble une tres bonne idée
